### PR TITLE
Fix float formatting when compiled to JavaScript

### PR DESCRIPTION
**Pull request by bergwerf**
This is practically a copy of #12 (its slightly more minimal). But it uses the latest master :).
There are still some issues left with JavaScript (e.g. check `pub run test --platform node`), but this fixes the most pressing one.

### CODE REVIEW

**Comment by Naddiseo** [comment]
Ah, so the root cause of this is the `String arg_str = _arg.toDouble().toString();` line. In JS, `(1.0).toString()` yields `"1"` which then doesn't match the regex for doubles.

My initial reaction to this PR is to reject it on the notion that string representations of doubles should always have a decimal separator (thus the regex is correct). However, I do agree that it could work as a fix. 
Another way I can think of fixing the issue is:
```diff
String arg_str = _arg.toDouble().toString();
+if (!arg_str.contains('.')) {
+    arg_str += '.0';
+ }
```

What do you think?

**Comment by bergwerf** [comment]
Hmm, it feels equally ad-hoc to me. I agree that changing the regex isn't really an elegant solution either. Perhaps it is possible to use `num.toStringAsPrecision` or `toStringAsFixed`, the float formatter should know what precision it wants. There is also an `toStringAsExponential`, using those would make the algorithm a bit cleaner/faster too (instead of trying the regexes one by one).

**Comment by Naddiseo** [comment]
I think I had considered using `toStringAsPrecision` and `toStringAsFixed`, but going back and checking, it looks like they wont (naively) work; a fair number of tests seem to round incorrectly.
I'm not really sure what the best solution is to this, it seems sprintf doesn't work well on node due to the number limits.

**Comment by bergwerf** [comment]
The number limits are a fundamental problem, but I thought with the introduction of `BigInt` these should be consistent between platforms. Can you add an example of the incorrect rounding? I did a few manual tests and it seems to round properly.

Another solution between directly using `toString` and manually generating a representation by taking out factors of 10 (or any base) could be to programmatically split into an integer and a fractional part, round both to the desired format,  and use `int.toString`.

I don't think taking out factors of 10 (digits) manually is a performance problem, but maybe there are other complications.

**Comment by Naddiseo** [comment]
Well, the naive change I did was `String arg_str = _arg.toDouble().toStringAsPrecision(options['precision'])`, however, the calculation for `options["precision"]` when using the "g" modifer depends on the init function already being run... a bit of an chicked-egg problem.

I don't think I can use `BigInt` because the problem is with doubles.. and the input is restrained to doubles. If I had a native `BigRat` I'd use that, but then this library would probably be pointless.

I'm still on/off looking for a way fix this, but it's not super high priority for me; I'm starting this consider accepting this PR, however I think it might not fix all the other issues I saw with number limits and whatnot.

**Comment by bergwerf** [comment]
The extreme cases with incompatible bounds also aren't critical. However the decimal point problem practically renders the whole library useless on the web (since rounded floats are formatted as 0), so this I would say is critical.

I don't really understand the mechanism well enough to judge if the chicken-egg problem is inherent. You could also try `toStringAsPrecision` with some maximum precision, but IMO all these are ad-hoc solutions in a way. For me sprintf is useful because it allows me to abbreviate a lot of calls to `toStringAsPrecision` and `padLeft`,

**Comment by bergwerf** [comment]
Oops, clicked a wrong button.

**Comment by bergwerf** [comment]
Ok one more comment; `toStringAsFixed` is the method that should be used to specified fractional digits (to precision specifies significant digits). And a solution you may like that is sort of a compromise first checks if the fractional part is zero, if it is then it uses `toStringAsFixed` to force at least one (0) fractional digit:
```dart
final arg_str = _arg == _arg.truncate() ? _arg.toStringAsFixed(1) : _arg.toString()
```

**Pull request closed without merging**
